=== fimdel/l2j-universe/l2j-universe-lindvior/Lindvior Source/dist/gameserver/data/stats/pc_parameters/class_data/class_data.dtd
<!ELEMENT list (class_data)*>
        <!ELEMENT class_data (lvl_up_data)*>
        <!ATTLIST class_data
                class_id CDATA #REQUIRED>

        <!ELEMENT lvl_up_data (lvl_add)*>
        <!ELEMENT lvl_add (#PCDATA)>
        <!ATTLIST lvl_add
                lvl CDATA #REQUIRED
                hp CDATA #REQUIRED
                mp CDATA #REQUIRED
                cp CDATA #REQUIRED>

=== fimdel/l2j-universe/l2j-universe-lindvior/Lindvior Source/dist/gameserver/data/stats/pc_parameters/class_data/[175] awaken2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright Mazaffaka Project (c) 2013.
  -->

<!DOCTYPE list SYSTEM "class_data.dtd">

<list>
    <class_data class_id="175">
        <lvl_up_data>
            <lvl_add lvl="1" cp="60.17874876" hp="100.2979146" mp="26.40264026"/>
            <lvl_add lvl="2" cp="69.39622642" hp="115.6603774" mp="36.20214395"/>
            <lvl_add lvl="3" cp="78.71499503" hp="131.1916584" mp="41.83767228"/>
            <lvl_add lvl="4" cp="88.13505462" hp="146.8917577" mp="47.53445636"/>
            <lvl_add lvl="5" cp="97.65640516" hp="162.7606753" mp="53.29249617"/>
            <lvl_add lvl="6" cp="107.2790467" hp="178.7984111" mp="59.11179173"/>
            <lvl_add lvl="7" cp="117.0029791" hp="195.0049652" mp="64.99234303"/>
            <lvl_add lvl="8" cp="126.8282026" hp="211.3803376" mp="70.93415008"/>
            <lvl_add lvl="9" cp="136.754717" hp="227.9245283" mp="76.93721286"/>
            <lvl_add lvl="10" cp="146.7825223" hp="244.6375372" mp="83.00153139"/>
            <lvl_add lvl="11" cp="156.9116187" hp="261.5193644" mp="89.12710567"/>
            <lvl_add lvl="12" cp="167.142006" hp="278.5700099" mp="95.31393568"/>
            <lvl_add lvl="13" cp="177.4736842" hp="295.7894737" mp="101.5620214"/>
            <lvl_add lvl="14" cp="187.9066534" hp="313.1777557" mp="107.8713629"/>
            <lvl_add lvl="15" cp="198.4409136" hp="330.734856" mp="114.2419602"/>
            <lvl_add lvl="16" cp="209.0764647" hp="348.4607746" mp="120.6738132"/>
            <lvl_add lvl="17" cp="219.8133069" hp="366.3555114" mp="127.1669219"/>
            <lvl_add lvl="18" cp="230.6514399" hp="384.4190665" mp="133.7212864"/>
            <lvl_add lvl="19" cp="241.590864" hp="402.6514399" mp="140.3369066"/>
            <lvl_add lvl="20" cp="252.6315789" hp="421.0526316" mp="147.0137825"/>
            <lvl_add lvl="21" cp="269.0168818" hp="448.3614697" mp="157.1209801"/>
            <lvl_add lvl="22" cp="285.551142" hp="475.91857" mp="167.3200613"/>
            <lvl_add lvl="23" cp="302.2343595" hp="503.7239325" mp="177.611026"/>
            <lvl_add lvl="24" cp="319.0665343" hp="531.7775571" mp="187.9938744"/>
            <lvl_add lvl="25" cp="336.0476663" hp="560.0794439" mp="198.4686064"/>
            <lvl_add lvl="26" cp="353.1777557" hp="588.6295929" mp="209.0352221"/>
            <lvl_add lvl="27" cp="370.4568024" hp="617.428004" mp="219.6937213"/>
            <lvl_add lvl="28" cp="387.8848064" hp="646.4746773" mp="230.4441041"/>
            <lvl_add lvl="29" cp="405.4617676" hp="675.7696127" mp="241.2863706"/>
            <lvl_add lvl="30" cp="423.1876862" hp="705.3128103" mp="252.2205207"/>
            <lvl_add lvl="31" cp="441.0625621" hp="735.1042701" mp="263.2465544"/>
            <lvl_add lvl="32" cp="459.0863952" hp="765.1439921" mp="274.3644717"/>
            <lvl_add lvl="33" cp="477.2591857" hp="795.4319762" mp="285.5742726"/>
            <lvl_add lvl="34" cp="495.5809335" hp="825.9682224" mp="296.8759571"/>
            <lvl_add lvl="35" cp="514.0516385" hp="856.7527309" mp="308.2695253"/>
            <lvl_add lvl="36" cp="532.6713009" hp="887.7855015" mp="319.754977"/>
            <lvl_add lvl="37" cp="551.4399206" hp="919.0665343" mp="331.3323124"/>
            <lvl_add lvl="38" cp="570.3574975" hp="950.5958292" mp="343.0015314"/>
            <lvl_add lvl="39" cp="589.4240318" hp="982.3733863" mp="354.762634"/>
            <lvl_add lvl="40" cp="608.6395233" hp="1014.399206" mp="366.6156202"/>
            <lvl_add lvl="41" cp="638.0734856" hp="1063.455809" mp="386.5237366"/>
            <lvl_add lvl="42" cp="667.733863" hp="1112.889772" mp="406.5849923"/>
            <lvl_add lvl="43" cp="697.6206554" hp="1162.701092" mp="426.7993874"/>
            <lvl_add lvl="44" cp="727.733863" hp="1212.889772" mp="447.1669219"/>
            <lvl_add lvl="45" cp="758.0734856" hp="1263.455809" mp="467.6875957"/>
            <lvl_add lvl="46" cp="788.6395233" hp="1314.399206" mp="488.3614089"/>
            <lvl_add lvl="47" cp="819.4319762" hp="1365.71996" mp="509.1883614"/>
            <lvl_add lvl="48" cp="850.4508441" hp="1417.418073" mp="530.1684533"/>
            <lvl_add lvl="49" cp="881.6961271" hp="1469.493545" mp="551.3016845"/>
            <lvl_add lvl="50" cp="913.1678252" hp="1521.946375" mp="572.5880551"/>
            <lvl_add lvl="51" cp="944.8659384" hp="1574.776564" mp="594.0275651"/>
            <lvl_add lvl="52" cp="976.7904667" hp="1627.984111" mp="615.6202144"/>
            <lvl_add lvl="53" cp="1008.94141" hp="1681.569017" mp="637.3660031"/>
            <lvl_add lvl="54" cp="1041.318769" hp="1735.531281" mp="659.2649311"/>
            <lvl_add lvl="55" cp="1073.922542" hp="1789.870904" mp="681.3169985"/>
            <lvl_add lvl="56" cp="1106.752731" hp="1844.587885" mp="703.5222052"/>
            <lvl_add lvl="57" cp="1139.809335" hp="1899.682224" mp="725.8805513"/>
            <lvl_add lvl="58" cp="1173.092354" hp="1955.153923" mp="748.3920368"/>
            <lvl_add lvl="59" cp="1206.601787" hp="2011.002979" mp="771.0566616"/>
            <lvl_add lvl="60" cp="1240.337637" hp="2067.229394" mp="793.8744257"/>
            <lvl_add lvl="61" cp="1274.299901" hp="2123.833168" mp="816.8453292"/>
            <lvl_add lvl="62" cp="1308.48858" hp="2180.8143" mp="839.9693721"/>
            <lvl_add lvl="63" cp="1342.903674" hp="2238.17279" mp="863.2465544"/>
            <lvl_add lvl="64" cp="1377.545184" hp="2295.90864" mp="886.676876"/>
            <lvl_add lvl="65" cp="1412.413108" hp="2354.021847" mp="910.2603369"/>
            <lvl_add lvl="66" cp="1447.507448" hp="2412.512413" mp="933.9969372"/>
            <lvl_add lvl="67" cp="1482.828203" hp="2471.380338" mp="957.8866769"/>
            <lvl_add lvl="68" cp="1518.375372" hp="2530.625621" mp="981.9295559"/>
            <lvl_add lvl="69" cp="1554.148957" hp="2590.248262" mp="1006.125574"/>
            <lvl_add lvl="70" cp="1590.148957" hp="2650.248262" mp="1030.474732"/>
            <lvl_add lvl="71" cp="1626.375372" hp="2710.625621" mp="1054.977029"/>
            <lvl_add lvl="72" cp="1662.828203" hp="2771.380338" mp="1079.632466"/>
            <lvl_add lvl="73" cp="1699.507448" hp="2832.512413" mp="1104.441041"/>
            <lvl_add lvl="74" cp="1736.413108" hp="2894.021847" mp="1129.402757"/>
            <lvl_add lvl="75" cp="1773.545184" hp="2955.90864" mp="1154.517611"/>
            <lvl_add lvl="76" cp="1810.903674" hp="3018.17279" mp="1179.785605"/>
            <lvl_add lvl="77" cp="1848.48858" hp="3080.8143" mp="1205.206738"/>
            <lvl_add lvl="78" cp="1886.299901" hp="3143.833168" mp="1230.781011"/>
            <lvl_add lvl="79" cp="1924.337637" hp="3207.229394" mp="1256.508423"/>
            <lvl_add lvl="80" cp="1962.601787" hp="3271.002979" mp="1282.388974"/>
            <lvl_add lvl="81" cp="2001.092354" hp="3335.153923" mp="1308.422665"/>
            <lvl_add lvl="82" cp="2039.809335" hp="3399.682224" mp="1334.609495"/>
            <lvl_add lvl="83" cp="2078.752731" hp="3464.587885" mp="1360.949464"/>
            <lvl_add lvl="84" cp="2117.922542" hp="3529.870904" mp="1387.442573"/>
            <lvl_add lvl="85" cp="9849.473684" hp="6486.888977" mp="2770.163859"/>
            <lvl_add lvl="86" cp="9946.700099" hp="6550.652433" mp="2822.767228"/>
            <lvl_add lvl="87" cp="10043.15293" hp="6614.393247" mp="2875.75804"/>
            <lvl_add lvl="88" cp="10141.83217" hp="6679.51142" mp="2928.667688"/>
            <lvl_add lvl="89" cp="10241.74479" hp="6745.006951" mp="2982.964778"/>
            <lvl_add lvl="90" cp="10341.88381" hp="6811.893744" mp="3035.180704"/>
            <lvl_add lvl="91" cp="10443.24926" hp="6877.150943" mp="3089.784074"/>
            <lvl_add lvl="92" cp="10545.84111" hp="6945.792453" mp="3144.774885"/>
            <lvl_add lvl="93" cp="10648.66634" hp="7013.811321" mp="3198.684533"/>
            <lvl_add lvl="94" cp="10753.71102" hp="7082.207547" mp="3253.981623"/>
            <lvl_add lvl="95" cp="10858.98908" hp="7151.988083" mp="3308.19755"/>
            <lvl_add lvl="96" cp="10965.49355" hp="7221.893744" mp="3364.800919"/>
            <lvl_add lvl="97" cp="11072.23138" hp="7292.169811" mp="3420.79173"/>
            <lvl_add lvl="98" cp="11181.18868" hp="7364.830189" mp="3476.701378"/>
            <lvl_add lvl="99" cp="11290.37934" hp="7476.87488" mp="3532.998469"/>
        </lvl_up_data>
    </class_data>
</list>

=== fimdel/l2j-universe/l2j-universe-lindvior/Lindvior Source/dist/gameserver/data/stats/pc_parameters/class_data/[146] algiza.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright Mazaffaka Project (c) 2013.
  -->

<!DOCTYPE list SYSTEM "class_data.dtd">

<list>
    <class_data class_id="146">
        <lvl_up_data>
            <lvl_add lvl="1" hp="101.0" mp="40.0" cp="90.9"/>
            <lvl_add lvl="2" hp="116.47" mp="47.28" cp="104.823"/>
            <lvl_add lvl="3" hp="132.11" mp="54.64" cp="118.899"/>
            <lvl_add lvl="4" hp="147.92" mp="62.08" cp="133.128"/>
            <lvl_add lvl="5" hp="163.9" mp="69.6" cp="147.51"/>
            <lvl_add lvl="6" hp="180.05" mp="77.2" cp="162.045"/>
            <lvl_add lvl="7" hp="196.37" mp="84.88" cp="176.733"/>
            <lvl_add lvl="8" hp="212.86" mp="92.64" cp="191.574"/>
            <lvl_add lvl="9" hp="229.52" mp="100.48" cp="206.568"/>
            <lvl_add lvl="10" hp="246.35" mp="108.4" cp="221.715"/>
            <lvl_add lvl="11" hp="263.35" mp="116.4" cp="237.015"/>
            <lvl_add lvl="12" hp="280.52" mp="124.48" cp="252.468"/>
            <lvl_add lvl="13" hp="297.86" mp="132.64" cp="268.074"/>
            <lvl_add lvl="14" hp="315.37" mp="140.88" cp="283.833"/>
            <lvl_add lvl="15" hp="333.05" mp="149.2" cp="299.745"/>
            <lvl_add lvl="16" hp="350.9" mp="157.6" cp="315.81"/>
            <lvl_add lvl="17" hp="368.92" mp="166.08" cp="332.028"/>
            <lvl_add lvl="18" hp="387.11" mp="174.64" cp="348.399"/>
            <lvl_add lvl="19" hp="405.47" mp="183.28" cp="364.923"/>
            <lvl_add lvl="20" hp="424.0" mp="192.0" cp="381.6"/>
            <lvl_add lvl="21" hp="458.1" mp="205.2" cp="412.29"/>
            <lvl_add lvl="22" hp="492.51" mp="218.52" cp="443.259"/>
            <lvl_add lvl="23" hp="527.23" mp="231.96" cp="474.507"/>
            <lvl_add lvl="24" hp="562.26" mp="245.52" cp="506.034"/>
            <lvl_add lvl="25" hp="597.6" mp="259.2" cp="537.84"/>
            <lvl_add lvl="26" hp="633.25" mp="273.0" cp="569.925"/>
            <lvl_add lvl="27" hp="669.21" mp="286.92" cp="602.289"/>
            <lvl_add lvl="28" hp="705.48" mp="300.96" cp="634.932"/>
            <lvl_add lvl="29" hp="742.06" mp="315.12" cp="667.854"/>
            <lvl_add lvl="30" hp="778.95" mp="329.4" cp="701.055"/>
            <lvl_add lvl="31" hp="816.15" mp="343.8" cp="734.535"/>
            <lvl_add lvl="32" hp="853.66" mp="358.32" cp="768.294"/>
            <lvl_add lvl="33" hp="891.48" mp="372.96" cp="802.332"/>
            <lvl_add lvl="34" hp="929.61" mp="387.72" cp="836.649"/>
            <lvl_add lvl="35" hp="968.05" mp="402.6" cp="871.245"/>
            <lvl_add lvl="36" hp="1006.8" mp="417.6" cp="906.12"/>
            <lvl_add lvl="37" hp="1045.86" mp="432.72" cp="941.274"/>
            <lvl_add lvl="38" hp="1085.23" mp="447.96" cp="976.707"/>
            <lvl_add lvl="39" hp="1124.91" mp="463.32" cp="1012.419"/>
            <lvl_add lvl="40" hp="1164.9" mp="478.8" cp="1048.41"/>
            <lvl_add lvl="41" hp="1214.3" mp="504.8" cp="1092.87"/>
            <lvl_add lvl="42" hp="1264.08" mp="531.0" cp="1137.672"/>
            <lvl_add lvl="43" hp="1314.24" mp="557.4" cp="1182.816"/>
            <lvl_add lvl="44" hp="1364.78" mp="584.0" cp="1228.302"/>
            <lvl_add lvl="45" hp="1415.7" mp="610.8" cp="1274.13"/>
            <lvl_add lvl="46" hp="1467.0" mp="637.8" cp="1320.3"/>
            <lvl_add lvl="47" hp="1518.68" mp="665.0" cp="1366.812"/>
            <lvl_add lvl="48" hp="1570.74" mp="692.4" cp="1413.666"/>
            <lvl_add lvl="49" hp="1623.18" mp="720.0" cp="1460.862"/>
            <lvl_add lvl="50" hp="1676.0" mp="747.8" cp="1508.4"/>
            <lvl_add lvl="51" hp="1729.2" mp="775.8" cp="1556.28"/>
            <lvl_add lvl="52" hp="1782.78" mp="804.0" cp="1604.502"/>
            <lvl_add lvl="53" hp="1836.74" mp="832.4" cp="1653.066"/>
            <lvl_add lvl="54" hp="1891.08" mp="861.0" cp="1701.972"/>
            <lvl_add lvl="55" hp="1945.8" mp="889.8" cp="1751.22"/>
            <lvl_add lvl="56" hp="2000.9" mp="918.8" cp="1800.81"/>
            <lvl_add lvl="57" hp="2056.38" mp="948.0" cp="1850.742"/>
            <lvl_add lvl="58" hp="2112.24" mp="977.4" cp="1901.016"/>
            <lvl_add lvl="59" hp="2168.48" mp="1007.0" cp="1951.632"/>
            <lvl_add lvl="60" hp="2225.1" mp="1036.8" cp="2002.59"/>
            <lvl_add lvl="61" hp="2282.1" mp="1066.8" cp="2053.89"/>
            <lvl_add lvl="62" hp="2339.48" mp="1097.0" cp="2105.532"/>
            <lvl_add lvl="63" hp="2397.24" mp="1127.4" cp="2157.516"/>
            <lvl_add lvl="64" hp="2455.38" mp="1158.0" cp="2209.842"/>
            <lvl_add lvl="65" hp="2513.9" mp="1188.8" cp="2262.51"/>
            <lvl_add lvl="66" hp="2572.8" mp="1219.8" cp="2315.52"/>
            <lvl_add lvl="67" hp="2632.08" mp="1251.0" cp="2368.872"/>
            <lvl_add lvl="68" hp="2691.74" mp="1282.4" cp="2422.566"/>
            <lvl_add lvl="69" hp="2751.78" mp="1314.0" cp="2476.602"/>
            <lvl_add lvl="70" hp="2812.2" mp="1345.8" cp="2530.98"/>
            <lvl_add lvl="71" hp="2873.0" mp="1377.8" cp="2585.7"/>
            <lvl_add lvl="72" hp="2934.18" mp="1410.0" cp="2640.762"/>
            <lvl_add lvl="73" hp="2995.74" mp="1442.4" cp="2696.166"/>
            <lvl_add lvl="74" hp="3057.68" mp="1475.0" cp="2751.912"/>
            <lvl_add lvl="75" hp="3120.0" mp="1507.8" cp="2808.0"/>
            <lvl_add lvl="76" hp="3182.7" mp="1540.8" cp="2864.43"/>
            <lvl_add lvl="77" hp="3245.78" mp="1574.0" cp="2921.202"/>
            <lvl_add lvl="78" hp="3309.24" mp="1607.4" cp="2978.316"/>
            <lvl_add lvl="79" hp="3373.08" mp="1641.0" cp="3035.772"/>
            <lvl_add lvl="80" hp="3437.3" mp="1674.8" cp="3093.57"/>
            <lvl_add lvl="81" hp="3501.9" mp="1708.8" cp="3151.71"/>
            <lvl_add lvl="82" hp="3566.88" mp="1743.0" cp="3210.192"/>
            <lvl_add lvl="83" hp="3632.24" mp="1777.4" cp="3269.016"/>
            <lvl_add lvl="84" hp="3697.98" mp="1812.0" cp="3328.182"/>
            <lvl_add lvl="85" hp="6718.53" mp="3693.6" cp="9091.79"/>
            <lvl_add lvl="86" hp="6784.4" mp="3763.6" cp="9180.92"/>
            <lvl_add lvl="87" hp="6850.91" mp="3834.0" cp="9270.93"/>
            <lvl_add lvl="88" hp="6918.08" mp="3904.8" cp="9361.82"/>
            <lvl_add lvl="89" hp="6985.9" mp="3976.0" cp="9453.6"/>
            <lvl_add lvl="90" hp="7054.39" mp="4047.6" cp="9546.29"/>
            <lvl_add lvl="91" hp="7123.55" mp="4119.6" cp="9639.88"/>
            <lvl_add lvl="92" hp="7193.39" mp="4192.0" cp="9734.39"/>
            <lvl_add lvl="93" hp="7263.92" mp="4264.8" cp="9829.82"/>
            <lvl_add lvl="94" hp="7335.13" mp="4338.0" cp="9926.19"/>
            <lvl_add lvl="95" hp="7407.04" mp="4411.6" cp="10023.51"/>
            <lvl_add lvl="96" hp="7479.66" mp="4485.6" cp="10121.78"/>
            <lvl_add lvl="97" hp="7552.99" mp="4560.0" cp="10221.01"/>
            <lvl_add lvl="98" hp="7627.04" mp="4634.8" cp="10321.22"/>
            <lvl_add lvl="99" hp="7701.81" mp="4710.0" cp="10422.4"/>
        </lvl_up_data>
    </class_data>
</list>
